[C dev] C_dev 작업물 병합
mementai-internship/workswave-frontend pull request #226
Opened 2024-10-21 13:12 UTC by juhee067

## 관련 이슈

## 주요 변경 사항
- 휴직관리 UI 개발
- 근로관리(출퇴근/근로/파트타이머) 필터 기능
- 본인 증명서 UI 수정
- 증명서 승인 모달 구현
- 출근 API 연결

## 스크린샷

## 전달사항(세심하게 봐야 할 부분 / 고민점)

2024-10-21 14:49 UTC, Seoin02 requested changes

2024-10-21 14:49 UTC, Seoin02 commented on src/apis/login.api.ts
> +  const { data } = await axiosInstance.post('/auth/login', { email, password });
이렇게 바꿨는데 로그인되나요?? 토큰 있는 상태로 로그인하면 안돼서 auth와 분리했어요

2024-10-21 14:49 UTC, Seoin02 commented on src/components/DocumentManagement/CertificationManagement/CertificationManagementDialog.tsx
> +interface FormData {
I붙여주세요

2024-10-22 01:05 UTC, sjlim32 commented on src/components/DocumentManagement/CertificationManagement/CertificationManagementDialog.tsx
> +interface FormData {
핫핫 넵 ㅎㅎ

2024-10-22 01:45 UTC, sjlim32 commented on src/apis/login.api.ts
> +  const { data } = await axiosInstance.post('/auth/login', { email, password });
현재 로컬 브랜치가 이상해서 dev에 다 merge 한 뒤 hotfix 파서 작업하겠습니다.

2024-10-22 01:45 UTC, Seoin02 approved these changes
고생하셨습니다!!

2024-10-22 01:45 UTC, sjlim32 approved these changes
고생하셨습니다 👍

2024-10-22 01:45 UTC, merged