[FEAT] 회원상세-정보 / UI 기획 수정 사항 반영
mementai-internship/workswave-frontend pull request #335
Opened 2024-10-30 16:07 UTC by Seoin02

## 관련 이슈

- #317 

## 주요 변경 사항
- 회원상세-정보 UI 기획 수정 사항 반영
- 증명서 신청 modal 구현

## 스크린샷

<img width="1047" alt="스크린샷 2024-10-31 오전 1 04 17" src="https://github.com/user-attachments/assets/81bb2ae9-64ec-458b-b357-b33f02b08288">

## 전달사항(세심하게 봐야 할 부분 / 고민점)

2024-10-30 22:17 UTC, juhee067 approved these changes
수고많으셨습니다!!

2024-10-31 00:26 UTC, davidktlee commented on src/components/MemberInfo/MemberBasicInfoTable.tsx
> +                          <MemberBasicInfoDatePicker
생년월일을 입력하기 위해 달력을 눌렀을 때, 현재부터 1달 씩 뒤로 갈 수 있어 조금 불편한 것 같은데 연도 선택도 가능하게 해주실 수 있나요..?

2024-10-31 00:30 UTC, davidktlee commented on src/components/MemberInfo/MemberInfoCommon/MemberInfoSelect.tsx
>    extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'content' | 'onChange' | 'style'> {
잘 몰라서 여쭤보는건데 그냥 타입 정의하지 않고 extends를 쓰신 이유가 있으신가요?

2024-10-31 00:35 UTC, davidktlee commented on src/components/MemberInfo/MemberInfoRegistrationNumber.tsx
> +        <p className="w-4 bg-white h-[22px] border border-2 border-gray-200 rounded-sm text-center">
border 스타일이 중복된 것 같습니다..!

2024-10-31 00:42 UTC, davidktlee requested changes
고생하셨습니다!
지금 주소 입력했을 때 api 수정 요청은 잘 가는 것 같은데 화면에 반영이 안되는 게 맞는 동작인거죠?!
그리고 주소 입력을 위해 주소 입력을 눌러 창이 뜰 때도 한 번 patch 요청이 가는데 그 부분도 한 번 확인해주시면 좋을 것 같습니다!

2024-10-31 00:56 UTC, Seoin02 commented on src/components/MemberInfo/MemberInfoCommon/MemberInfoSelect.tsx
>    extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'content' | 'onChange' | 'style'> {
Button 타입을 다 적용할 수 있게 해봤습니다

2024-10-31 00:58 UTC, Seoin02 commented on src/components/MemberInfo/MemberBasicInfoTable.tsx
> +                          <MemberBasicInfoDatePicker
네 다음 pr에 반영하겠습니다 좋은 피드백 감삼당

2024-10-31 00:59 UTC, davidktlee approved these changes
👍

2024-10-31 01:00 UTC, merged