[FEAT] OT 관리 페이지 조회 API 연결 및 필터 검색 구현
mementai-internship/workswave-frontend pull request #336
Opened 2024-10-30 16:45 UTC by dudwns

## 관련 이슈
- #300 
## 주요 변경 사항
- OT 내역을 지점, 파트, 상태, 날짜, 이름, 전화번호로 필터 검색 할 수 있도록 구현
- OT 신청 시 날짜를 두 번 클릭하면 생기는 오류 수정
- 메모를 작성하지 않으면 OT를 신청할 수 없도록 수정

## 스크린샷

## 전달사항(세심하게 봐야 할 부분 / 고민점)
연차 승인은 API 문제로 인해 500 에러가 발생합니다. (백엔드 수정 예정)

2024-10-30 22:17 UTC, juhee067 approved these changes
수고많으셨습니다!!

2024-10-31 00:48 UTC, davidktlee requested changes
현재 연차관리 페이지의 select에서 파트를 선택했을 때 url 의 branch_id가 바뀌는 현상이 있습니다!
-> 확인해보니 이번 pr에 하신 작업은 아닌 것 같은데 영준님 부분이라 변경 부탁드리겠습니다!

2024-10-31 01:05 UTC, davidktlee commented on src/hooks/apis/useOvertime.ts
> +    queryKey: [QUERY_KEYS.overtimes, data],
post나 patch를 해도 새로고침 되지 않게 하기 위해 data를 넣으신 걸까요?

2024-10-31 01:20 UTC, dudwns commented
> * 현재 연차관리 페이지의 select에서 파트를 선택했을 때 url 의 branch_id가 바뀌는 현상이 있습니다!
>   -> 확인해보니 이번 pr에 하신 작업은 아닌 것 같은데 영준님 부분이라 변경 부탁드리겠습니다!
> * 가운데 정렬이 되면 좋을 것 같습니다..!
> 
> <img alt="스크린샷 2024-10-31 오전 9 55 59" width="1391" src="https://private-user-images.githubusercontent.com/97086762/381784182-af69cde5-6c08-48f8-83af-341951b3fdfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzY4MTYsIm5iZiI6MTczMDMzNjUxNiwicGF0aCI6Ii85NzA4Njc2Mi8zODE3ODQxODItYWY2OWNkZTUtNmMwOC00OGY4LTgzYWYtMzQxOTUxYjNmZGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxMDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NzFmYjkzY2VkZWY3ZDY5M2Y2MGNjN2EwMTQ1NmMzMzllNjI4MzE2NzZkZDdlMzI1MmRmMDg4Y2I5Y2IxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hDbllSxAxmjzLuy3mg9Hu13b7YXYHXnW7jpSxnk4ubI">

- 연차 관리는 - 수정한 API가 아직 반영이 안돼서 #294 에서 수정 할 예정입니다!

- 가운데 정렬 수정하였습니다!
![image](https://github.com/user-attachments/assets/828d6b32-5cff-4158-9e1f-a199ce715b44)

2024-10-31 01:26 UTC, dudwns commented on src/hooks/apis/useOvertime.ts
> +    queryKey: [QUERY_KEYS.overtimes, data],
data(url의 params)가 변경되면 자동으로 새로운 데이터를 불러오도록 하기위해 queryKey에 추가했습니다.
(refetch와 invalidateQueries를 일일이 작성하지 않아도 새로 불러와지도록 수정 하었습니다.)

2024-10-31 01:40 UTC, merged