[FEAT] 회원상세 - 정보 / API 연결
mementai-internship/workswave-frontend pull request #356
Opened 2024-10-31 13:55 UTC by Seoin02

## 관련 이슈

- #341 

## 주요 변경 사항
- 완료: 지점 변경 / 이름 변경 / 전화번호 변경 / 성별 변경 / 메일 변경
- API 필드 추가 필요(연결X): 경력 입력 / 휴직 등록 / 영문이름 변경 / 외국인 여부 입력 / 생년월일 변경 / 학력 입력 / 주소 입력 / 재입사자 입력
- API 논의 필요: 권한 변경

## 스크린샷

## 전달사항(세심하게 봐야 할 부분 / 고민점)

- 생년월일 입력 datePicker 연도선택 가능한 옵션 공통 컴포넌트 제작한 성준님과 상의 후 교체하겠습니다. @davidktlee

2024-10-31 23:50 UTC, davidktlee commented on src/components/MemberInfo/MemberInfoPopover/RequestDocs.tsx
> +export type TDocsType = '퇴직증명서' | '재직증명서' | '경력증명서' | '그 외 증명서' | null;
이 타입을 사용하는 곳은 `MemberInfoPage` 파일 하나인데 사용하지 않는 곳에서 선언하고 export 한 이유가 있으실까요?

2024-10-31 23:57 UTC, davidktlee commented on src/hooks/apis/useUserManagement.ts
> +      queryClient.invalidateQueries({
패치 할 때만 회원 관리 리스트를 refetch 하시는 이유가 무엇인가요?
삭제 시에는 왜 안하는지 궁금합니다..!

2024-10-31 23:59 UTC, davidktlee requested changes
고생하셨습니다!
지금 주민번호 열람 하기 / 닫기 할 때도 api 요청이 가는데 한 번 확인 부탁드릴게요!

2024-11-01 00:45 UTC, Seoin02 commented on src/components/MemberInfo/MemberInfoPopover/RequestDocs.tsx
> +export type TDocsType = '퇴직증명서' | '재직증명서' | '경력증명서' | '그 외 증명서' | null;
파일 분리하다가 놓쳤습니다 수정하겠습니다

2024-11-01 00:45 UTC, Seoin02 commented on src/hooks/apis/useUserManagement.ts
> +      queryClient.invalidateQueries({
수정하겠습니다

2024-11-01 00:49 UTC, davidktlee approved these changes

2024-11-01 01:05 UTC, merged