[A조] 급여계산표 페이지 / UI
mementai-internship/workswave-frontend pull request #46
Opened 2024-10-13 03:07 UTC by memento-HYEMIN

## 관련 이슈

- #21 

## 주요 변경 사항
- 급여계산표 페이지 UI 제작
- 급여계산하는 함수 로직 작성 (utils)

## 스크린샷

- 기본 UI
![스크린샷 2024-10-13 오전 11 12 24](https://github.com/user-attachments/assets/41e6e0f9-7874-41bd-a9d3-7ff33fcb1742)

- 브라우저가 작아졌을 때의 UI
![image](https://github.com/user-attachments/assets/c8b3798c-84fe-4566-828e-3684f7f8bf16)

## 전달사항(세심하게 봐야 할 부분 / 고민점)

- 표에 작성되는 내용들이 많아 1720px미만일 경우 표의 형태가 깨지는 이슈가 발생하여, 브라우저의 넓이가 1720px 미만일 경우 overflow-x-scroll 속성을 사용하여 옆으로 스크롤하도록 코드를 작성했습니다.
- UI 제작을 위해 작성해두었던 더미 데이터들은 api 연결할 때, 삭제하겠습니다.

2024-10-13 06:39 UTC, davidktlee requested changes
고생하셨습니다!
궁금한 부분 리뷰 남겨 놓았습니다!

2024-10-13 06:39 UTC, davidktlee commented on src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
> +        <h3 className="text-xl">급여구간표</h3>
저희 사용하기로 했던 Title 컴포넌트를 쓰면 좋을 것 같습니다!

2024-10-13 06:39 UTC, davidktlee commented on src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
> +  const headerTdCommonStyle = 'px-2';
한 군데에서만 사용하는데 변수로 빼신 이유가 있으실까요?!

2024-10-13 06:39 UTC, davidktlee commented on src/pages/basicSetting/SalaryRangePage.tsx
> +      <div className="max-w-[1722px] mx-auto w-full overflow-x-scroll border ${SALARY_RANGE_BORDER_COLOR}">
오타이신 것 같은데 템플릿 리터럴이 적용 되고 있지 않습니다!🥲

2024-10-13 06:39 UTC, davidktlee commented on src/components/BasicSetting/SalaryRange/SalaryRangeCalcResult.tsx
> +          borderStyle={`border-r border-b ${SALARY_RANGE_BORDER_COLOR} border-t border-t-[#333333] border-l border-l-[#333333]`}
어떤 부분은 border 컬러를 직접 주시고 어떤 부분은 `SALARY_RANGE_BORDER_COLOR` 를 사용하셨는데 다르게 사용하신 이유가 있으실까요?

2024-10-13 06:39 UTC, davidktlee commented on src/components/BasicSetting/SalaryRange/SalaryRangeTableTd.tsx
> +    ${typeof text === 'number' ? 'text-right' : 'text-center'} ${styles ? styles : ''}`;
`styles` 부분도 `borderStyle` 부분처럼 단순 할당해도 좋을 것 같습니다!

2024-10-13 06:39 UTC, davidktlee commented on src/utils/calculatedSalaryRange.ts
> +export const calculateSalaryResult = (salary: number) => {
계산 할 때 현재 input의 속성은 단순 number로 들어가있어서 - 값을 입력하면 에러가 납니다.
validation 로직이 추가되면 좋을 것 같아요!
또 월급을 입력했을 때 연봉이 월급 값으로 바뀌어 버리는 것도 수정되면 좋을 것 같습니다!!

2024-10-13 07:19 UTC, memento-HYEMIN commented on src/pages/basicSetting/SalaryRangePage.tsx
> +      <div className="max-w-[1722px] mx-auto w-full overflow-x-scroll border ${SALARY_RANGE_BORDER_COLOR}">
헉 코드 분리하면서 오타가 났나보네요🥲 확인했습니다!

2024-10-13 07:24 UTC, memento-HYEMIN commented on src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
> +  const headerTdCommonStyle = 'px-2';
코드 변경하면서 놓친 것 같습니다. 이 부분 수정하겠습니다!

2024-10-13 07:34 UTC, memento-HYEMIN commented on src/components/BasicSetting/SalaryRange/SalaryRangeTableTd.tsx
> +    ${typeof text === 'number' ? 'text-right' : 'text-center'} ${styles ? styles : ''}`;
styles로 아무 것도 입력 받지 않으면 class에 undefined가 남아서 삼항연산자를 사용했습니다...! styles props에 기본값 설정하고, 클래스에는 단순 할당하는 방식으로 변경하겠습니다!

2024-10-13 07:46 UTC, davidktlee commented on src/components/BasicSetting/SalaryRange/SalaryRangeTableTd.tsx
> +    ${typeof text === 'number' ? 'text-right' : 'text-center'} ${styles ? styles : ''}`;
저도 undefined가 부분은 몰랐네요! 저도 수정해야겠네요!

2024-10-13 09:23 UTC, davidktlee approved these changes

2024-10-13 23:18 UTC, davidktlee requested changes
혜민님 const 폴더명 한 번 확인 하고 머지 하면 좋을 것 같습니다!

2024-10-14 03:42 UTC, davidktlee approved these changes
👍

2024-10-14 03:50 UTC, merged